name: daily new words

on:
  schedule:
    - cron:  '0 12 * * *'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: run daily new words
      run: cd ./server && go test ./test/ && go run ./cmd/ && cd ../
      
    - uses: EndBug/add-and-commit@v9
      with:
        message: 'add daily new words json'
        add: '.'  
