name: daily new words

on:
  schedule:
    - cron:  '0 12 * * *'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5.4.0
      with:
        go-version: 1.18
    - name: test
      run: cd ./server && go test ./test/ && cd ../

    - name: run daily new words
      run: cd ./server && go run ./cmd/ && cd ../
      
    - uses: EndBug/add-and-commit@v9
      with:
        message: 'add daily new words json'
        add: '.'  
